name: Java CI with Gradle

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Set up Gradle (wrapper)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Optional: specify version if needed
          # gradle-version: '8.9'

      # 4. Build project using Gradle Wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # 5. Optional: run tests
      - name: Run tests
        run: ./gradlew test
