name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle manually
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle wrapper --gradle-version 8.7

      - name: Give permission to Gradlew
        run: chmod +x gradlew || true

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if [ -f AndroidManifest.xml ]; then
            mv AndroidManifest.xml app/src/main/
            echo "✅ Moved AndroidManifest.xml"
          fi

          if [ -f build.gradle ]; then
            if grep -q "com.android.application" build.gradle; then
              mv build.gradle app/
              echo "✅ Moved app build.gradle"
            fi
          fi

          for file in *.xml; do
            if [ -f "$file" ]; then
              mv "$file" app/src/main/res/
              echo "✅ Moved $file to res/"
            fi
          done

          for file in *.kt; do
            if [ -f "$file" ]; then
              mv "$file" app/src/main/java/
              echo "✅ Moved $file to java/"
            fi
          done

          echo "🎉 Structure fixed!"

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if [ -f AndroidManifest.xml ]; then
            mv AndroidManifest.xml app/src/main/
            echo "✅ Moved AndroidManifest.xml"
          fi

          if [ -f build.gradle ]; then
            if grep -q "com.android.application" build.gradle; then
              mv build.gradle app/
              echo "✅ Moved app build.gradle"
            fi
          fi

          for file in *.xml; do
            if [ -f "$file" ]; then
              mv "$file" app/src/main/res/
              echo "✅ Moved $file to res/"
            fi
          done

          for file in *.kt; do
            if [ -f "$file" ]; then
              mv "$file" app/src/main/java/
              echo "✅ Moved $file to java/"
            fi
          done

          echo "🎉 Structure fixed!"

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
