name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.2"
          yes | sdkmanager --licenses || true

      - name: Setup Gradle wrapper
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi
          chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        timeout-minutes: 15

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
