name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Make gradlew executable
        run: |
          ls -la
          chmod +x ./gradlew
          ls -la gradlew
      
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        timeout-minutes: 15
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
